//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAND_ORGS
    {
        public int LOT_ID { get; set; }
        public int ORG_ID { get; set; }
        public string BRAND_BARCODE { get; set; }
        public double UNIT { get; set; }
        public double BASEPRICE { get; set; }
        public double QUANTITY { get; set; }
        public double INNN { get; set; }
        public  double OUTTTT { get; set; }
    
        public virtual PRODUCT_BRANDS PRODUCT_BRANDS { get; set; }
        public virtual ORGANISATIONS ORGANISATIONS { get; set; }
    }
}
