//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAND_ORGS
    {
        public int LOT_ID { get; set; }
        public int ORG_ID { get; set; }
        public int BRAND_BARCODE { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<double> INNN { get; set; }
        public Nullable<double> OUTTTT { get; set; }
    }
}
