//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOW
    {
        public int Source_LOT_ID { get; set; }
        public int Source_ORG_ID { get; set; }
        public int Target_LOT_ID { get; set; }
        public int Target_ORG_ID { get; set; }
        public int BRAND_BARCODE { get; set; }
        public int QUANTITY { get; set; }
        public System.DateTime FlowDate { get; set; }
    }
}
