//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANUFACTURERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANUFACTURERS()
        {
            this.PRODUCT_BRANDS = new HashSet<PRODUCT_BRANDS>();
        }
    
        public int MANUFACTURER_ID { get; set; }
        public string MANUFACTURER_NAME { get; set; }
        public string MANUFACTURER_ADDRESS { get; set; }
        public Nullable<int> CITY { get; set; }
        public string Country_Code { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual COUNTRY_CITY COUNTRY_CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_BRANDS> PRODUCT_BRANDS { get; set; }
    }
}
