//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANISATIONS
    {
        public int ORG_ID { get; set; }
        public string ORG_NAME { get; set; }
        public int PARENT_ORG { get; set; }
        public byte[] ORG_ABSTRACT { get; set; }
        public string ORG_ADDRESS { get; set; }
        public Nullable<int> ORG_CITY { get; set; }
        public byte[] ORG_TYPE { get; set; }
    }
}
