//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_BRANDS
    {
        public int MANUFACTURER_ID { get; set; }
        public int M_SYSCODE { get; set; }
        public string BRAND_BARCODE { get; set; }
        public string BRAND_NAME { get; set; }
    }
}
