//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int M_SYSCODE { get; set; }
        public string M_CODE { get; set; }
        public string M_NAME { get; set; }
        public string M_SHORTNAME { get; set; }
        public string M_PARENTCODE { get; set; }
        public byte[] M_ABSTRACT { get; set; }
        public string M_CATEGORY { get; set; }
        public byte[] IS_ACTIVE { get; set; }
    }
}
