//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bil372_Odev1_Grup6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_FEATURES
    {
        public Nullable<int> M_SYSCODE { get; set; }
        public Nullable<int> FEATURE_ID { get; set; }
        public double MINVAL { get; set; }
        public double MAXVAL { get; set; }
    
        public virtual FEATURES FEATURES { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
